# Generated by Django 5.0.3 on 2026-01-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergh',
            name='name',
            field=models.CharField(help_text='Введите Ваше имя', max_length=25, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='usergh',
            name='patronymic',
            field=models.CharField(blank=True, help_text='Введите Ваше отчество (если имеется)', max_length=25, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='usergh',
            name='phone',
            field=models.CharField(help_text='Введите Ваш телефон', max_length=15, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='usergh',
            name='post',
            field=models.CharField(help_text='Введите Вашу должность', max_length=35, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='usergh',
            name='surname',
            field=models.CharField(help_text='Введите Вашу фамилию', max_length=25, verbose_name='Фамилия'),
        ),
    ]
