# Generated by Django 5.0.3 on 2026-01-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('sensor_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID датчика')),
                ('parameter', models.CharField(help_text='Введите параметр датчика', max_length=25, verbose_name='Параметр')),
                ('code', models.CharField(help_text='Введите кодовое сокращение', max_length=15, verbose_name='Кодовое сокращение')),
                ('unit', models.CharField(help_text='Введите единицу измерения', max_length=10, verbose_name='Единица измерения')),
                ('description', models.TextField(blank=True, help_text='Введите описание', null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Датчик',
                'verbose_name_plural': 'Датчики',
                'db_table': 'sensors',
            },
        ),
    ]
