# Generated by Django 5.0.3 on 2026-01-05 20:02

import django.db.models.deletion
import pgvector.django
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFromSensors',
            fields=[
                ('data_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID данных')),
                ('datetime', models.DateTimeField(auto_now_add=True, help_text='Выберите дату и время показаний', verbose_name='Время и дата показаний')),
                ('humidity', models.FloatField(help_text='Введите влажность воздуха', verbose_name='Влажность воздуха')),
                ('air_temp', models.FloatField(help_text='Введите температуру воздуха', verbose_name='Температура воздуха')),
                ('sol_temp', models.FloatField(help_text='Введите температуру раствора', verbose_name='Температура раствора')),
                ('water_level', models.FloatField(help_text='Введите уровень воды в баке', verbose_name='Уровень воды в баке')),
                ('ec', models.FloatField(help_text='Введите EC', verbose_name='EC')),
                ('lux', models.FloatField(help_text='Введите Lux', verbose_name='Lux')),
                ('ph', models.FloatField(help_text='Введите pH', verbose_name='pH')),
            ],
            options={
                'verbose_name': 'Показания датчиков',
                'verbose_name_plural': 'Показания датчиков',
                'db_table': 'data_from_sensors',
            },
        ),
        migrations.CreateModel(
            name='NormalValues',
            fields=[
                ('values_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID нормальных значений')),
                ('minimum', models.FloatField(help_text='Введите минимально допустимое значение', verbose_name='Минимально допустимое значение')),
                ('maximum', models.FloatField(help_text='Введите максимально допустимое значение', verbose_name='Максимально допустимое значение')),
                ('optimum', models.FloatField(help_text='Введите оптимальное значение', verbose_name='Оптимальное значение')),
                ('critical_minimum', models.FloatField(help_text='Введите критический минимум', verbose_name='Критический минимум')),
                ('critical_maximum', models.FloatField(help_text='Введите критический максимум', verbose_name='Критический максимум')),
                ('sensor', models.ForeignKey(help_text='Выберите параметр из списка', on_delete=django.db.models.deletion.CASCADE, to='monitoring.sensor', verbose_name='Параметр')),
            ],
            options={
                'verbose_name': 'Нормальные значения',
                'verbose_name_plural': 'Нормальные значения',
                'db_table': 'normal_values',
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('solution_id', models.IntegerField(help_text='Введите ID решения', primary_key=True, serialize=False, verbose_name='ID решения')),
                ('recommendation', models.TextField(help_text='Введите рекомендацию для устранению аварии', verbose_name='Рекомендация для устранения аварии')),
                ('arguments', models.TextField(help_text='Введите аргументы для устранения аварии', verbose_name='Аргументы для устранения аварии')),
                ('comment', models.TextField(blank=True, default='Авария устранена', help_text='Введите комментарий об устранении аварии', verbose_name='Комментарий об устранении аварии')),
                ('user', models.ForeignKey(help_text='Выберите пользователя, устранившего аварию, из списка', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Аварию устранил пользователь')),
            ],
            options={
                'verbose_name': 'Описание устранения аварии',
                'verbose_name_plural': 'Описания устранения аварий',
                'db_table': 'solutions',
            },
        ),
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('accident_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID аварии')),
                ('description', models.TextField(help_text='Введите устранение аварии', verbose_name='Описание аварии')),
                ('status', models.CharField(choices=[('New', 'Новая'), ('Eliminated', 'Устранена'), ('Not_eliminated', 'Не устранена')], default='New', help_text='Выберите статус из списка', max_length=15, verbose_name='Статус')),
                ('eliminated_datetime', models.DateTimeField(blank=True, help_text='Выберите дату и время устранения аварии', null=True, verbose_name='Время и дата устранения аварии')),
                ('embedding', pgvector.django.VectorField(dimensions=3584, editable=False, verbose_name='Эмбеддниг описания аварии')),
                ('data_from_sensors', models.ForeignKey(help_text='Выберите показания датчиков по дате из списка', on_delete=django.db.models.deletion.DO_NOTHING, to='monitoring.datafromsensors', verbose_name='Показания датчиков')),
                ('solution', models.ForeignKey(blank=True, help_text='Выберите устранение аварии из списка по ID (оно соответствует ID аварии)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='monitoring.solution', verbose_name='Устранение аварии')),
            ],
            options={
                'verbose_name': 'Авария',
                'verbose_name_plural': 'Аварии',
                'db_table': 'accidents',
            },
        ),
    ]
