# Generated by Django 5.0.3 on 2026-04-12 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Выберите пользователя, устранившего аварию, из списка', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Аварию устранил пользователь'),
        ),
        migrations.AddField(
            model_name='accident',
            name='solution',
            field=models.OneToOneField(blank=True, help_text='Выберите устранение аварии из списка по ID (оно соответствует ID аварии)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='monitoring.solution', verbose_name='Устранение аварии'),
        ),
    ]
