# Generated by Django 5.0.3 on 2026-01-06 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_datafromsensors_normalvalues_solution_accident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='data_from_sensors',
            field=models.OneToOneField(help_text='Выберите показания датчиков по дате из списка', on_delete=django.db.models.deletion.DO_NOTHING, to='monitoring.datafromsensors', verbose_name='Показания датчиков'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='solution',
            field=models.OneToOneField(blank=True, help_text='Выберите устранение аварии из списка по ID (оно соответствует ID аварии)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='monitoring.solution', verbose_name='Устранение аварии'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('eliminated', 'Устранена'), ('not_eliminated', 'Не устранена')], default='new', help_text='Выберите статус из списка', max_length=15, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='normalvalues',
            name='sensor',
            field=models.OneToOneField(help_text='Выберите параметр из списка', on_delete=django.db.models.deletion.CASCADE, to='monitoring.sensor', verbose_name='Параметр'),
        ),
    ]
