# Generated by Django 5.0.3 on 2026-01-18 18:21

from django.db import migrations, models
from django.conf import settings

class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_alter_accident_data_from_sensors_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Solution',
            name='user',
            field=models.ForeignKey(
                settings.AUTH_USER_MODEL,
                on_delete=models.DO_NOTHING,
                verbose_name="Аварию устранил пользователь",
                help_text="Выберите пользователя, устранившего аварию, из списка"
            )
        ),
    ]
