# Generated by Django 5.0.3 on 2026-02-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_auto_20260118_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='parameter',
            field=models.CharField(help_text='Введите параметр датчика', max_length=25, unique=True, verbose_name='Параметр'),
        ),
    ]
