# Generated by Django 5.0.3 on 2026-03-17 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_alter_sensor_parameter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='comment',
            field=models.TextField(blank=True, default='Авария устранена в соответствии с рекомендацией', help_text='Введите комментарий об устранении аварии', null=True, verbose_name='Комментарий об устранении аварии'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='solution_id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID решения'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Выберите пользователя, устранившего аварию, из списка', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Аварию устранил пользователь'),
        ),
    ]
