# Generated by Django 5.0.3 on 2026-03-17 11:01

import pgvector.django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_alter_solution_comment_alter_solution_solution_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='embedding',
            field=pgvector.django.VectorField(dimensions=512, editable=False, verbose_name='Эмбеддниг описания аварии'),
        ),
    ]
