# Generated by Django 5.0.3 on 2026-03-18 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_alter_accident_embedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accident',
            name='embedding',
        ),
    ]
