# Generated by Django 5.0.3 on 2026-05-05 16:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID локации')),
                ('code', models.CharField(help_text='Введите код локации', max_length=50, unique=True, verbose_name='Код локации')),
                ('description', models.TextField(blank=True, help_text='Введите описание (например, подсказка где найти)', null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('plant_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID растения')),
                ('title', models.CharField(help_text='Введите название растения', max_length=80, unique=True, verbose_name='Навзание растения')),
                ('description', models.TextField(blank=True, help_text='Введите описание растения', null=True, verbose_name='Описание растения')),
            ],
            options={
                'verbose_name': 'Растение',
                'verbose_name_plural': 'Растения',
                'db_table': 'plants',
            },
        ),
        migrations.CreateModel(
            name='Planting',
            fields=[
                ('planting_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID посадки')),
                ('datetime', models.DateTimeField(auto_now_add=True, help_text='Выберите дату и время посадки', verbose_name='Дата и время посадки')),
                ('status', models.CharField(blank=True, choices=[('completed', 'Завершено'), ('growing', 'Растёт'), ('dead', 'Погибло')], default='growing', help_text='Выберите статус из списка', max_length=15, verbose_name='Статус')),
                ('location', models.ForeignKey(blank=True, help_text='Выберите локацию из списка', null=True, on_delete=django.db.models.deletion.SET_NULL, to='todolist.location', verbose_name='Локация')),
                ('plant', models.ForeignKey(help_text='Выберите растение из списка', on_delete=django.db.models.deletion.CASCADE, to='todolist.plant', verbose_name='Растение')),
            ],
            options={
                'verbose_name': 'Посадка',
                'verbose_name_plural': 'Посадки',
                'db_table': 'plantings',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('stage_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Стадия роста')),
                ('title', models.CharField(help_text='Введите название', max_length=80, verbose_name='Название')),
                ('duration', models.PositiveIntegerField(help_text='Введите продолжительность в днях', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Продолжительность в днях')),
                ('start_day', models.IntegerField(blank=True, default=0, help_text='Будет заполнено автоматически', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Начальный день')),
                ('finish_day', models.PositiveIntegerField(blank=True, help_text='Будет заполнено автоматически', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Конечный день')),
                ('order', models.PositiveIntegerField(help_text='Введите порядок в цикле роста', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Порядок в цикле роста')),
                ('plant', models.ForeignKey(help_text='Выберите растение из списка', on_delete=django.db.models.deletion.CASCADE, to='todolist.plant', verbose_name='Растение')),
            ],
            options={
                'verbose_name': 'Стадия роста',
                'verbose_name_plural': 'Стадии роста',
                'db_table': 'stages',
                'unique_together': {('plant', 'title')},
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('action_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID действия')),
                ('title', models.CharField(help_text='Введите название', max_length=80, verbose_name='Название')),
                ('periodicity', models.CharField(choices=[('once', 'Однократно'), ('every_day', 'Каждый день'), ('every_n_day', 'Каждые N дней')], default='every_day', help_text='Выберите периодичность из списка', max_length=15, verbose_name='Периодичность')),
                ('interval', models.PositiveIntegerField(blank=True, help_text='Введите интервал дней N (только для периодичности "Каждые N дней")', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Интервал дней')),
                ('instruction', models.TextField(blank=True, help_text='Введите инструкцию', null=True, verbose_name='Инструкция')),
                ('stage', models.ForeignKey(help_text='Выберите стадию роста из списка', on_delete=django.db.models.deletion.CASCADE, to='todolist.stage', verbose_name='Стадия роста')),
            ],
            options={
                'verbose_name': 'Действие',
                'verbose_name_plural': 'Действия',
                'db_table': 'actions',
                'unique_together': {('stage', 'title')},
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID задачи')),
                ('date', models.DateField(auto_now_add=True, help_text='Выберите дату и время задачи', verbose_name='Дата и время задачи')),
                ('status', models.CharField(choices=[('await', 'Ожидает'), ('done', 'Выполнено'), ('missed', 'Просрочено')], default='await', help_text='Выберите статус из списка', max_length=15, verbose_name='Статус')),
                ('eliminated_datetime', models.DateTimeField(blank=True, help_text='Выберите дату и время выполнения задачи', null=True, verbose_name='Время и дата выполнения задачи')),
                ('action', models.ForeignKey(help_text='Выберите действие из списка', on_delete=django.db.models.deletion.CASCADE, to='todolist.action', verbose_name='Действие')),
                ('executor', models.ForeignKey(blank=True, help_text='Выберите пользователя, выполнившего задание, из списка', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Задание выполнил пользователь')),
                ('planting', models.ForeignKey(help_text='Выберите посадку из списка', on_delete=django.db.models.deletion.CASCADE, to='todolist.planting', verbose_name='Посадка')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'db_table': 'tasks',
                'unique_together': {('date', 'action', 'planting')},
            },
        ),
    ]
