# Generated by Django 5.0.3 on 2026-01-06 11:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID локации')),
                ('code', models.CharField(help_text='Введите код локации', max_length=10, verbose_name='Код локации')),
                ('description', models.TextField(blank=True, help_text='Введите описание (например, подсказка где найти)', null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('plant_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID растения')),
                ('title', models.CharField(help_text='Введите название растения', max_length=25, verbose_name='Навзание растения')),
                ('description', models.TextField(blank=True, help_text='Введите описание растения', null=True, verbose_name='Описание растения')),
            ],
            options={
                'verbose_name': 'Растение',
                'verbose_name_plural': 'Растения',
                'db_table': 'plants',
            },
        ),
        migrations.CreateModel(
            name='Planting',
            fields=[
                ('planting_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID посадки')),
                ('datetime', models.DateTimeField(auto_now_add=True, help_text='Выберите дату и время посадки', verbose_name='Дата и время посадки')),
                ('location', models.ForeignKey(blank=True, help_text='Выберите локацию из списка', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='todolist.location', verbose_name='Локация')),
                ('plant', models.ForeignKey(help_text='Выберите растение из списка', on_delete=django.db.models.deletion.CASCADE, to='todolist.plant', verbose_name='Растение')),
            ],
            options={
                'verbose_name': 'Посадка',
                'verbose_name_plural': 'Посадки',
                'db_table': 'plantings',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('stage_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Стадия роста')),
                ('title', models.CharField(help_text='Введите название', max_length=25, verbose_name='Название')),
                ('duration', models.PositiveIntegerField(help_text='Введите продолжительность в днях', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Продолжительность в днях')),
                ('order', models.PositiveIntegerField(help_text='Введите порядок в цикле роста', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Порядок в цикле роста')),
                ('plant', models.ForeignKey(help_text='Выберите растение из списка', on_delete=django.db.models.deletion.CASCADE, to='todolist.plant', verbose_name='Растение')),
            ],
            options={
                'verbose_name': 'Стадия роста',
                'verbose_name_plural': 'Стадии роста',
                'db_table': 'stages',
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('task_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID действия')),
                ('title', models.CharField(help_text='Введите название', max_length=25, verbose_name='Название')),
                ('periodicity', models.CharField(choices=[('once', 'Однократно'), ('every_day', 'Каждый день'), ('every_n_day', 'Каждые N дней')], default='every_day', help_text='Выберите периодичность из списка', max_length=15, verbose_name='Периодичность')),
                ('interval', models.PositiveIntegerField(blank=True, help_text='Введите интервал дней (только для периодичности "Каждые N дней")', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Интервал дней')),
                ('description', models.TextField(blank=True, help_text='Введите описание (инструкцию)', null=True, verbose_name='Описание (инструкциия)')),
                ('stage', models.OneToOneField(help_text='Выберите стадию роста из списка', on_delete=django.db.models.deletion.CASCADE, to='todolist.stage', verbose_name='Стадия роста')),
            ],
            options={
                'verbose_name': 'Действие',
                'verbose_name_plural': 'Действия',
                'db_table': 'actions',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID задачи')),
                ('date', models.DateField(auto_now_add=True, help_text='Выберите дату и время задачи', verbose_name='Дата и время задачи')),
                ('status', models.CharField(choices=[('await', 'Ожидает'), ('done', 'Выполнено'), ('missed', 'Просрочено')], default='await', help_text='Выберите статус из списка', max_length=15, verbose_name='Статус')),
                ('eliminated_datetime', models.DateTimeField(blank=True, help_text='Выберите дату и время выполнения задачи', null=True, verbose_name='Время и дата выполнения задачи')),
                ('action', models.OneToOneField(help_text='Выберите действие из списка', on_delete=django.db.models.deletion.CASCADE, to='todolist.action', verbose_name='Действие')),
                ('planting', models.ForeignKey(help_text='Выберите посадку из списка', on_delete=django.db.models.deletion.CASCADE, to='todolist.planting', verbose_name='Посадка')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'db_table': 'tasks',
            },
        ),
    ]
