# Generated by Django 5.0.3 on 2026-04-12 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('todolist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='executor',
            field=models.ForeignKey(blank=True, help_text='Выберите пользователя, выполнившего задание, из списка', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Задание выполнил пользователь'),
        ),
        migrations.AddField(
            model_name='task',
            name='planting',
            field=models.ForeignKey(help_text='Выберите посадку из списка', on_delete=django.db.models.deletion.CASCADE, to='todolist.planting', verbose_name='Посадка'),
        ),
        migrations.AlterUniqueTogether(
            name='stage',
            unique_together={('plant', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='action',
            unique_together={('stage', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('date', 'action', 'planting')},
        ),
    ]
