# Generated by Django 5.0.3 on 2026-01-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='task_id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID действия'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID локации'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='plant_id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID растения'),
        ),
        migrations.AlterField(
            model_name='planting',
            name='planting_id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID посадки'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='stage_id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='Стадия роста'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID задачи'),
        ),
    ]
