# Generated by Django 5.0.3 on 2026-01-15 10:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_alter_action_task_id_alter_location_location_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='finish_day',
            field=models.PositiveIntegerField(blank=True, help_text='Будет заполнено автоматически', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Конечный день'),
        ),
        migrations.AddField(
            model_name='stage',
            name='start_day',
            field=models.IntegerField(blank=True, default=0, help_text='Будет заполнено автоматически', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Начальный день'),
        ),
    ]
