# Generated by Django 5.0.3 on 2026-01-17 16:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_stage_finish_day_stage_start_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='interval',
            field=models.PositiveIntegerField(blank=True, help_text='Введите интервал дней (только для периодичности "Каждые N дней")', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Интервал дней'),
        ),
        migrations.AlterField(
            model_name='action',
            name='stage',
            field=models.ForeignKey(help_text='Выберите стадию роста из списка', on_delete=django.db.models.deletion.CASCADE, to='todolist.stage', verbose_name='Стадия роста'),
        ),
    ]
