# Generated by Django 5.0.3 on 2026-01-17 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_alter_action_interval_alter_action_stage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='Action',
            old_name='task_id',
            new_name='action_id',
        ),
    ]
