# Generated by Django 5.0.3 on 2026-01-17 20:40

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_auto_20260117_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='Action',
            old_name='description',
            new_name='instruction',
        ),
        migrations.AlterField(
            model_name='Action',
            name='instruction',  # поле, у которого меняем help_text
            field=models.TextField(
                null=True,
                blank=True,
                verbose_name="Инструкция",
                help_text="Введите инструкцию"
            ),
        ),
    ]
