# Generated by Django 5.0.3 on 2026-01-18 18:27

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_auto_20260117_2340'),
        ('users', "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name='Task',
            name='executor',
            field=models.ForeignKey(
                settings.AUTH_USER_MODEL,
                on_delete=models.DO_NOTHING,
                verbose_name="Задание выполнил пользователь",
                help_text="Выберите пользователя, выполнившего задание, из списка"
            ),
        ),
    ]
