# Generated by Django 5.0.3 on 2026-01-20 22:11

from django.db import migrations, models
from apps.todolist.models import Planting, MAX_STATUS_LENGTH

class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0007_auto_20260118_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='Planting',
            name='status',
            field=models.CharField(
                choices=Planting.Status.choices,
                default=Planting.Status.GROWING,
                max_length=MAX_STATUS_LENGTH,
                null=False,
                blank=True,
                verbose_name="Статус",
                help_text="Выберите статус из списка"
            )
        ),
    ]
