# Generated by Django 5.0.3 on 2026-01-21 17:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0008_auto_20260121_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='interval',
            field=models.PositiveIntegerField(blank=True, help_text='Введите интервал дней N (только для периодичности "Каждые N дней")', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Интервал дней'),
        ),
        migrations.AlterField(
            model_name='action',
            name='title',
            field=models.CharField(help_text='Введите название', max_length=45, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='title',
            field=models.CharField(help_text='Введите название растения', max_length=45, verbose_name='Навзание растения'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='title',
            field=models.CharField(help_text='Введите название', max_length=45, verbose_name='Название'),
        ),
    ]
