# Generated by Django 5.0.3 on 2026-01-21 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0010_alter_task_executor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='action',
            field=models.ForeignKey(help_text='Выберите действие из списка', on_delete=django.db.models.deletion.CASCADE, to='todolist.action', verbose_name='Действие'),
        ),
    ]
