# Generated by Django 5.0.3 on 2026-01-21 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0011_alter_task_action'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('date', 'action', 'planting')},
        ),
    ]
