# Generated by Django 5.0.3 on 2026-01-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0012_alter_task_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='title',
            field=models.CharField(help_text='Введите название', max_length=80, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='title',
            field=models.CharField(help_text='Введите название растения', max_length=80, verbose_name='Навзание растения'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='title',
            field=models.CharField(help_text='Введите название', max_length=80, verbose_name='Название'),
        ),
    ]
