# Generated by Django 5.0.3 on 2026-01-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0013_alter_action_title_alter_plant_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(help_text='Выберите дату и время задачи', verbose_name='Дата и время задачи'),
        ),
    ]
