# Generated by Django 5.0.3 on 2026-01-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0014_alter_task_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(auto_now_add=True, help_text='Выберите дату и время задачи', verbose_name='Дата и время задачи'),
        ),
    ]
