# Generated by Django 5.0.3 on 2026-02-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0015_alter_task_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='code',
            field=models.CharField(help_text='Введите код локации', max_length=10, unique=True, verbose_name='Код локации'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='title',
            field=models.CharField(help_text='Введите название растения', max_length=80, unique=True, verbose_name='Навзание растения'),
        ),
        migrations.AlterUniqueTogether(
            name='action',
            unique_together={('stage', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='stage',
            unique_together={('plant', 'title')},
        ),
    ]
